---

# $(lsb_release -sc)
- name: Add universe
  # apt_repository: repo='universe'
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu saucy universe'

- name: Add virtualbox repo key
  shell: wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -

- name: Add Virtualbox repo
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian saucy contrib'

- name: Add Intel gpu drivers repo
  shell: wget -q https://download.01.org/gfx/RPM-GPG-KEY-ilg -O- | sudo apt-key add -
  tags: intelgpu
    
- name: Add intel gpu drivers repo 2
  shell: wget -q https://download.01.org/gfx/RPM-GPG-KEY-ilg-2 -O- | sudo apt-key add -
  tags: intelgpu

- name: add docker repo key
  apt_key: id=A88D21E9 url=https://get.docker.io/gpg

- name: Add Docker repo
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main'

- name: Increase fs watch handle limit
  sysctl: name="fs.inotify.max_user_watches" state=present reload="yes" checks="both" value="1048576"

- name: disable ipv6 step 1
  sysctl: name="net.ipv6.conf.all.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: disable ipv6 step 2
  sysctl: name="net.ipv6.conf.default.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: disable ipv6 step 3
  sysctl: name="net.ipv6.conf.lo.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/iptables.rules
  notify: restart iptables

