---

- name: disable ipv6 step 1
  sysctl: name="net.ipv6.conf.all.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: disable ipv6 step 2
  sysctl: name="net.ipv6.conf.default.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: disable ipv6 step 3
  sysctl: name="net.ipv6.conf.lo.disable_ipv6" state=present reload="yes" checks="both" value="1"

- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/iptables.rules
  notify: restart iptables

